# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: it

pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
  - name: SpacyNLP
    model: "it_core_news_md"
    case_sensitive: False
  - name: SpacyTokenizer
    intent_tokenization_flag: False
    intent_split_symbol: "*"
    token_pattern: None
  - name: SpacyFeaturizer
    pooling: "mean"
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 10
  - name: DIETClassifier
    epochs: 300
    constrain_similarities: True
    model_confidence: 'linear_norm'
  #- name: SpacyEntityExtractor
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 300
    constrain_similarities: True
    model_confidence: 'linear_norm'

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
   - name: RulePolicy
#     nlu_threshold: 0.1
#     ambiguity_threshold: 0.1
#     core_threshold: 0.1
#     fallback_action_name: "no action_listen"
     core_fallback_threshold: 0.1
     core_fallback_action_name: "action_default_fallback"
     enable_fallback_prediction: True
   - name: MemoizationPolicy
   - name: TEDPolicy
     core_fallback_threshold: 0.1
     core_fallback_action_name: "action_default_fallback"
     enable_fallback_prediction: True
     max_history: 5
     epochs: 300
     constrain_similarities: True
     model_confidence: 'linear_norm'


