# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: it

pipeline:
  - name: LanguageModelTokenizer
  - name: LanguageModelFeaturizer
    model_weights: "dbmdz/bert-base-italian-xxl-uncased"
    model_name: "bert"
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 10
  - name: DIETClassifier
    epochs: 300
    constrain_similarities: True
    model_confidence: 'linear_norm'
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 300
    model_confidence: 'linear_norm'
    constrain_similarities: True

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
   - name: RulePolicy
     core_fallback_threshold: 0.1
     core_fallback_action_name: "action_default_fallback"
     enable_fallback_prediction: True
   - name: MemoizationPolicy
   - name: TEDPolicy
     max_history: 5
     core_fallback_threshold: 0.1
     core_fallback_action_name: "action_default_fallback"
     enable_fallback_prediction: True
     epochs: 300
     constrain_similarities: True
     model_confidence: 'linear_norm'

